cross_validation:
  method: 'expanding window'
  window_size_first_pass: 730
  window_size_last_pass: 910
  n_passes: 3
  forecasting_window_size: 7

metrics:
  - rmse
  - mase

modeling:
  approach: HW-ES
  trend: 'additive'
  damped_trend: True
  seasonal: 'multiplicative'
  seasonal_periods: 365
  target_timeseries:
    - 'DEF0C'
    - 'DE111'

