cv:
    scheme: expanding window
    relsize_shortest_train_window: 0.6  # 1.0 is the inference dataset size
    n_passes: 3
    steps_ahead: 1
    size_forecast_window: 7


modeling:
  approach: HW-ES
  mode: districtwise
  model_inference_window:
      start: 2013-01-01
      end: 2015-06-22
  test_window:
      start: 2015-06-23
      end: 2015-06-29
  preprocessing:
      - get_quantile_equivalent_normal_dist
      - make_strictly_positive
  hyperpars:
      trend: additive
      seasonal: multiplicative
      seasonal_periods: 7
  targets:
      - DEF0C
      - DEF07
      - DEF0B
      - DEF05
      - DEF0E


evaluation:
  - MAE
  - RMSE
