evaluation:
  rolling_window:
    n_splits: 2
  metrics: rmse, mae

experiments:
  forecasting_approaches: hw-es, arima

training:
# STANDARD
#  approach: approach-name
#    hyperpar: hyperpar-value

  hw-es:
    trend: 'mul'
    damped_trend: True
    seasonal: 'mul'
    seasonal_periods: 365
    use_boxcox: False
    # exog_names: None

  arima:


