cross-validation:
  window_size_first_pass: 365
  window_size_last_pass: 540
  n_passes: 3
  forecasting_window_size: 7

metrics:
  - rmse
  - mae

training:
# STANDARD
#  approach: approach-name
#    hyperpar: hyperpar-value
  trend: 'mul'
  damped_trend: True
  seasonal: 'mul'
  seasonal_periods: 365
  use_boxcox: False
  # exog_names: None

